import { useState, useRef } from "react";

export default function AudioUploader() {
  const [file, setFile] = useState(null);
    const [audioUrl, setAudioUrl] = useState(null);
      const [isUploading, setIsUploading] = useState(false);
        const [error, setError] = useState(null);
          const [dragActive, setDragActive] = useState(false);

              const fileInputRef = useRef(null);

                const handleDrag = (e) => {
                    e.preventDefault();
                        e.stopPropagation();
                            if (e.type === "dragenter" || e.type === "dragover") {
                                  setDragActive(true);
                                      } else if (e.type === "dragleave") {
                                            setDragActive(false);
                                                }
                                                  };

                                                    const handleDrop = (e) => {
                                                        e.preventDefault();
                                                            e.stopPropagation();
                                                                setDragActive(false);

                                                                        if (e.dataTransfer.files && e.dataTransfer.files[0]) {
                                                                              const droppedFile = e.dataTransfer.files[0];
                                                                                    console.log("File dropped:", droppedFile.name, droppedFile.type, droppedFile.size);

                                                                                                if (droppedFile.type.startsWith("audio/")) {
                                                                                                        setFile(droppedFile);
                                                                                                                setError(null);
                                                                                                                      } else {
                                                                                                                              console.error("Invalid file drop. Type:", droppedFile.type);
                                                                                                                                      setError("Please select a valid audio file.");
                                                                                                                                            }
                                                                                                                                                }
                                                                                                                                                  };

                                                                                                                                                    const handleChange = (e) => {
                                                                                                                                                        if (e.target.files && e.target.files[0]) {
                                                                                                                                                              const selectedFile = e.target.files[0];
                                                                                                                                                                    console.log("File selected:", selectedFile.name, selectedFile.type, selectedFile.size);
                                                                                                                                                                          setFile(selectedFile);
                                                                                                                                                                                setError(null);
                                                                                                                                                                                    }
                                                                                                                                                                                      };

                                                                                                                                                                                        const triggerFileSelect = () => {
                                                                                                                                                                                            fileInputRef.current.click();
                                                                                                                                                                                              };

                                                                                                                                                                                                const handleUpload = async () => {
                                                                                                                                                                                                    if (!file) return;

                                                                                                                                                                                                        console.log("=== Starting Upload Process ===");
                                                                                                                                                                                                            console.log("Payload:", file.name, file.type, file.size);

                                                                                                                                                                                                                setIsUploading(true);
                                                                                                                                                                                                                    setError(null);

                                                                                                                                                                                                                        const formData = new FormData();
                                                                                                                                                                                                                            formData.append("audio", file);

                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                      console.log("Sending POST request to http://localhost:3001/api/upload");
                                                                                                                                                                                                                                            const response = await fetch("http://localhost:3001/api/upload", {
                                                                                                                                                                                                                                                    method: "POST",
                                                                                                                                                                                                                                                            body: formData,
                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                        console.log("Response status:", response.status, response.statusText);

                                                                                                                                                                                                                                                                              if (!response.ok) {
                                                                                                                                                                                                                                                                                      let errorMessage = "Upload failed.";
                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                        const errData = await response.json();
                                                                                                                                                                                                                                                                                                                  console.error("Server error payload:", errData);
                                                                                                                                                                                                                                                                                                                            errorMessage = errData.message || errorMessage;
                                                                                                                                                                                                                                                                                                                                    } catch (parseError) {
                                                                                                                                                                                                                                                                                                                                              console.error("Failed to parse server error response", parseError);
                                                                                                                                                                                                                                                                                                                                                        errorMessage = `Server returned status code - ${response.status}`;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        throw new Error(errorMessage);
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                    const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                          console.log("Upload successful! Response payload:", data);

                                                                                                                                                                                                                                                                                                                                                                                                      setAudioUrl(data.url);
                                                                                                                                                                                                                                                                                                                                                                                                            setFile(null);
                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                      console.error("Upload caught an exception:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                            setError(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                      setIsUploading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("=== Upload Process Ended ===");
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`drop-zone ${dragActive ? "drag-active" : ""}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onDragEnter={handleDrag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onDragLeave={handleDrag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onDragOver={handleDrag}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onDrop={handleDrop}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={triggerFileSelect}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ref={fileInputRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          accept="audio/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={isUploading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <svg 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="upload-icon" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          viewBox="0 0 24 24" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fill="none" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stroke="currentColor" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strokeWidth="1.5" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  strokeLinecap="round" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            strokeLinejoin="round"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <polyline points="17 8 12 3 7 8" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <line x1="12" y1="3" x2="12" y2="15" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </svg>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>{file ? "Change file" : "Click or drag audio file here"}</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {file && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="file-name">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {file.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="submit-btn" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleUpload}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={!file || isUploading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isUploading ? "Uploading..." : "Upload Audio"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="error-message">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {audioUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="success-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>Playback</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <audio className="audio-player" controls src={audioUrl} autoPlay>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Your browser does not support the audio element.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </audio>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a className="link-btn" href={audioUrl} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Open Direct Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
