import { useState, useEffect } from "react";

export default function AudioLibrary() {
  const [audioFiles, setAudioFiles] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
      const [error, setError] = useState(null);

        useEffect(() => {
            const fetchAudioFiles = async () => {
                  try {
                          const response = await fetch("http://localhost:3001/api/audio");

                                          if (!response.ok) {
                                                    throw new Error(`Server returned status code - ${response.status}`);
                                                            }

                                                                    const data = await response.json();
                                                                            setAudioFiles(data);
                                                                                  } catch (err) {
                                                                                          setError(err.message);
                                                                                                } finally {
                                                                                                        setIsLoading(false);
                                                                                                              }
                                                                                                                  };

                                                                                                                      fetchAudioFiles();
                                                                                                                        }, []);

                                                                                                                          const formatFilename = (publicId) => {
                                                                                                                              const filename = publicId.replace("audio_uploads/", "");
                                                                                                                                  const parts = filename.split("_");
                                                                                                                                      if (parts.length > 1) {
                                                                                                                                            parts.pop(); 
                                                                                                                                                  return parts.join("_");
                                                                                                                                                      }
                                                                                                                                                          return filename;
                                                                                                                                                            };

                                                                                                                                                              const formatDate = (dateString) => {
                                                                                                                                                                  return new Date(dateString).toLocaleDateString("en-US", {
                                                                                                                                                                        month: "short",
                                                                                                                                                                              day: "numeric",
                                                                                                                                                                                    year: "numeric"
                                                                                                                                                                                        });
                                                                                                                                                                                          };

                                                                                                                                                                                            if (isLoading) {
                                                                                                                                                                                                return <div className="loading-state">Fetching audio library...</div>;
                                                                                                                                                                                                  }

                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                        return <div className="error-message">{error}</div>;
                                                                                                                                                                                                          }

                                                                                                                                                                                                            if (audioFiles.length === 0) {
                                                                                                                                                                                                                return <div className="loading-state">No audio files found.</div>;
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                        <div className="library-container">
                                                                                                                                                                                                                              {audioFiles.map((file) => (
                                                                                                                                                                                                                                      <div key={file.asset_id || file.public_id} className="audio-card">
                                                                                                                                                                                                                                                <div className="audio-title">
                                                                                                                                                                                                                                                            <span>{formatFilename(file.public_id)}</span>
                                                                                                                                                                                                                                                                        <span className="audio-date">{formatDate(file.created_at)}</span>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                            <audio 
                                                                                                                                                                                                                                                                                                        className="audio-player" 
                                                                                                                                                                                                                                                                                                                    controls 
                                                                                                                                                                                                                                                                                                                                preload="none"
                                                                                                                                                                                                                                                                                                                                            src={file.secure_url}
                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                  Your browser does not support the audio element.
                                                                                                                                                                                                                                                                                                                                                                            </audio>
                                                                                                                                                                                                                                                                                                                                                                                      <a 
                                                                                                                                                                                                                                                                                                                                                                                                  className="link-btn" 
                                                                                                                                                                                                                                                                                                                                                                                                              style={{ marginTop: '0.5rem', fontSize: '0.8rem', padding: '0.5rem' }} 
                                                                                                                                                                                                                                                                                                                                                                                                                          href={file.secure_url} 
                                                                                                                                                                                                                                                                                                                                                                                                                                      target="_blank" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                  rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Open Source
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
